### PR TITLE
Allow Arbitrarily More Attributes in `[metadata]` and `[options]` Sections

### LINKED ISSUE #5: circleci check yaml file
Instead of making a web request to CircleCI servers to check if it is being used, just check for the circleci yaml file in the repo.  This is faster and generates less traffic on their servers.  Also, in the scenario they are having problems, it doesn't stop the action or result in a mis-detection.

### PR DESCRIPTION
**Pull request by ric-evans**
Essentially, if the builder doesn't need to know about some arbitrary `[metadata]` attribute, leave it alone.

closes https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/3
closes https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/8
closes https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/4
closes #5

### CODE REVIEW

**Comment by dsschult** [comment]
I think that looks ok?  This is where a test would really help.  Is there a way to run a github action pointed at a branch/pr?

**Comment by ric-evans** [comment]
> I think that looks ok? This is where a test would really help. Is there a way to run a github action pointed at a branch/pr?

I could work on this: https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/4

**Comment by ric-evans** [comment]
> Is there a way to run a github action pointed at a branch/pr?

You may be able to use the branch as a tag, I know that works for github pip-requirements

**Comment by ric-evans** [comment]
bump version to `1.3`, both here and in https://github.com/WIPACrepo/wipac-dev-tools/blob/main/.github/workflows/wipac-cicd.yml

**Comment by ric-evans** [comment]
:man_facepalming: `package_data` and `scripts` are in the `[options]` section, not `[metadata]`. We need to apply same dev to `[options]` section.

**Comment by ric-evans** [comment]
closes https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/4

**Pull request merged**
